### ISSUE TITLE
Tagged build "1.0.0-rc.14" actually contains kappa "1.0.0-rc.11"

### ISSUE THREAD

**Issue by pgaubatz** [jasisk/docker-kappa#1]
Hi,

as I ran into this issue with kappa https://github.com/krakenjs/kappa/issues/97 I wanted to try `1.0.0-rc.14` when I realized that the tagged build on https://hub.docker.com/r/sisk/kappa/tags/ still contained `kappa 1.0.0-rc.11`...

Any plans on re-releasing a "real" `1.0.0-rc.14`? Otherwise I'll just copy your `Dockerfile` and build it myself... :smile: 
Cheers,
Patrick

**Comment by jasisk** [comment]
Ack. Super sorry. Not sure why I wasn't getting notifications for this but the fixed build was tagged a couple of weeks ago. Terribly sorry for the trouble!
